from __future__ import annotations

import json
import re
import unicodedata
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = ROOT / "assignment_player_sport_data.js"
SOURCE_URL = "https://disney.fandom.com/wiki/Category:Disney_characters"
API_URL = "https://disney.fandom.com/api.php"
SOURCE_NAME = "Disney Wiki Disney characters category"


def main() -> None:
    data = load_data()
    names = fetch_disney_names()
    players: dict[str, dict[str, Any]] = data.setdefault("players", {})
    for name in sorted(names, key=str.lower):
        key = player_key(name)
        if key:
            players[key] = {"sport": "disney", "displayName": name}

    sources = [
        source
        for source in data.get("sources", [])
        if str(source.get("name") or "") != SOURCE_NAME
    ]
    sources.append({
        "name": SOURCE_NAME,
        "sport": "disney",
        "url": SOURCE_URL,
        "count": len(names),
    })
    data["sources"] = sources
    data["generatedAt"] = datetime.now(timezone.utc).isoformat(timespec="milliseconds").replace("+00:00", "Z")
    write_data(data)
    print(f"Imported {len(names)} Disney character names from {SOURCE_URL}")


def fetch_disney_names() -> set[str]:
    names: set[str] = set()
    cmcontinue = ""
    while True:
        params = {
            "action": "query",
            "list": "categorymembers",
            "cmtitle": "Category:Disney characters",
            "cmnamespace": "0",
            "cmlimit": "500",
            "format": "json",
        }
        if cmcontinue:
            params["cmcontinue"] = cmcontinue
        url = f"{API_URL}?{urllib.parse.urlencode(params)}"
        payload = fetch_json(url)
        for item in payload.get("query", {}).get("categorymembers", []):
            title = clean_title(item.get("title", ""))
            if useful_name(title):
                names.add(title)
        cmcontinue = payload.get("continue", {}).get("cmcontinue", "")
        if not cmcontinue:
            return names


def fetch_json(url: str) -> dict[str, Any]:
    request = urllib.request.Request(url, headers={"User-Agent": "CardPipeline/1.0"})
    with urllib.request.urlopen(request, timeout=45) as response:
        return json.loads(response.read().decode("utf-8", "ignore"))


def clean_title(value: str) -> str:
    text = str(value or "").strip()
    text = re.sub(r"\s+", " ", text)
    return text


def useful_name(value: str) -> bool:
    text = str(value or "").strip()
    lowered = text.lower()
    if len(text) < 2 or len(text) > 120:
        return False
    blocked_prefixes = ("category:", "file:", "template:", "disney wiki:")
    return not lowered.startswith(blocked_prefixes)


def load_data() -> dict[str, Any]:
    raw = DATA_PATH.read_text(encoding="utf-8")
    match = re.search(r"window\.AutoSheetReviewPlayerSports\s*=\s*(\{.*?\})\s*;\s*\}\)\(\);", raw, re.S)
    if not match:
        raise RuntimeError(f"Could not parse {DATA_PATH}")
    return json.loads(match.group(1))


def write_data(data: dict[str, Any]) -> None:
    payload = json.dumps(data, indent=2, ensure_ascii=False, sort_keys=True)
    DATA_PATH.write_text(
        "// Generated by category import scripts. Do not edit by hand.\n"
        "(function exposePlayerSportData() {\n"
        f"  window.AutoSheetReviewPlayerSports = {payload};\n"
        "})();\n",
        encoding="utf-8",
    )


def player_key(value: str) -> str:
    text = strip_accents(value).lower()
    text = re.sub(r"[^a-z0-9.' -]+", " ", text)
    return re.sub(r"\s+", " ", text).strip()


def strip_accents(value: str) -> str:
    return "".join(
        char
        for char in unicodedata.normalize("NFKD", str(value or ""))
        if not unicodedata.combining(char)
    )


if __name__ == "__main__":
    main()
