from __future__ import annotations

import html
import json
import re
import subprocess
import unicodedata
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = ROOT / "assignment_player_sport_data.js"
SOURCE_URL = "https://bloodyelbow.com/2016/07/11/mma-news-the-complete-list-of-the-ufcs-200-greatest-fighters-of-all-time/"
SOURCE_NAME = "Bloody Elbow UFC 200 greatest fighters list"


def main() -> None:
    data = load_data()
    names = fetch_ufc_names()
    players: dict[str, dict[str, Any]] = data.setdefault("players", {})
    for name in sorted(names, key=str.lower):
        key = player_key(name)
        if key:
            players[key] = {"sport": "ufc", "displayName": name}

    sources = [
        source
        for source in data.get("sources", [])
        if str(source.get("name") or "") != SOURCE_NAME
    ]
    sources.append({
        "name": SOURCE_NAME,
        "sport": "ufc",
        "url": SOURCE_URL,
        "count": len(names),
    })
    data["sources"] = sources
    data["generatedAt"] = datetime.now(timezone.utc).isoformat(timespec="milliseconds").replace("+00:00", "Z")
    write_data(data)
    print(f"Imported {len(names)} UFC fighter names from {SOURCE_URL}")


def fetch_ufc_names() -> list[str]:
    raw = fetch_text(SOURCE_URL)
    names_by_rank: dict[int, str] = {}
    pattern = re.compile(r"<p[^>]*>\s*(\d{1,3})(?:\s*\([^)]*\))?\s*[–-]\s*(.*?)\s*</p>", re.I | re.S)
    for match in pattern.finditer(raw):
        rank = int(match.group(1))
        if rank < 1 or rank > 200:
            continue
        name = clean_label(match.group(2))
        if useful_name(name):
            names_by_rank[rank] = name
    return [names_by_rank[rank] for rank in sorted(names_by_rank)]


def fetch_text(url: str) -> str:
    request = urllib.request.Request(
        url,
        headers={
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
            "(KHTML, like Gecko) Chrome/125.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "Accept-Language": "en-US,en;q=0.9",
        },
    )
    try:
        with urllib.request.urlopen(request, timeout=45) as response:
            return response.read().decode("utf-8", "ignore")
    except Exception:
        result = subprocess.run(
            [
                "curl.exe",
                "-L",
                "-A",
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
                url,
            ],
            check=True,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="ignore",
        )
        return result.stdout


def clean_label(value: str) -> str:
    text = re.sub(r"<[^>]+>", " ", value)
    text = html.unescape(text)
    text = normalize_quotes(text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def normalize_quotes(value: str) -> str:
    return (
        str(value or "")
        .replace("“", '"')
        .replace("”", '"')
        .replace("‘", "'")
        .replace("’", "'")
    )


def useful_name(value: str) -> bool:
    text = str(value or "").strip()
    lowered = text.lower()
    if len(text) < 2 or len(text) > 90:
        return False
    blocked = {"yes", "no", "fighter", "fighters"}
    return lowered not in blocked and not lowered.isdigit()


def load_data() -> dict[str, Any]:
    raw = DATA_PATH.read_text(encoding="utf-8")
    match = re.search(r"window\.AutoSheetReviewPlayerSports\s*=\s*(\{.*?\})\s*;\s*\}\)\(\);", raw, re.S)
    if not match:
        raise RuntimeError(f"Could not parse {DATA_PATH}")
    return json.loads(match.group(1))


def write_data(data: dict[str, Any]) -> None:
    payload = json.dumps(data, indent=2, ensure_ascii=False, sort_keys=True)
    DATA_PATH.write_text(
        "// Generated by category import scripts. Do not edit by hand.\n"
        "(function exposePlayerSportData() {\n"
        f"  window.AutoSheetReviewPlayerSports = {payload};\n"
        "})();\n",
        encoding="utf-8",
    )


def player_key(value: str) -> str:
    text = strip_accents(value).lower()
    text = re.sub(r"[^a-z0-9.' -]+", " ", text)
    return re.sub(r"\s+", " ", text).strip()


def strip_accents(value: str) -> str:
    return "".join(
        char
        for char in unicodedata.normalize("NFKD", str(value or ""))
        if not unicodedata.combining(char)
    )


if __name__ == "__main__":
    main()
