from __future__ import annotations

import html
import json
import re
import subprocess
import unicodedata
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = ROOT / "assignment_player_sport_data.js"
SOURCE_URL = "https://comicvine.gamespot.com/profile/stockholm45/lists/top-200-star-wars-characters/60246/"
SOURCE_NAME = "Comic Vine top Star Wars characters list"


def main() -> None:
    data = load_data()
    names = fetch_star_wars_names()
    players: dict[str, dict[str, Any]] = data.setdefault("players", {})
    for name in sorted(names, key=str.lower):
        key = player_key(name)
        if key:
            players[key] = {"sport": "star wars", "displayName": name}

    sources = [
        source
        for source in data.get("sources", [])
        if str(source.get("name") or "") != SOURCE_NAME
    ]
    sources.append({
        "name": SOURCE_NAME,
        "sport": "star wars",
        "url": SOURCE_URL,
        "count": len(names),
    })
    data["sources"] = sources
    data["generatedAt"] = datetime.now(timezone.utc).isoformat(timespec="milliseconds").replace("+00:00", "Z")
    write_data(data)
    print(f"Imported {len(names)} Star Wars character names from {SOURCE_URL}")


def fetch_star_wars_names() -> set[str]:
    names: set[str] = set()
    for url in (SOURCE_URL, f"{SOURCE_URL}?page=2"):
        raw = fetch_text(url)
        for match in re.finditer(r'<a\b[^>]*href=["\'][^"\']*/4005-\d+/["\'][^>]*>\s*<h3>(.*?)</h3>', raw, re.I | re.S):
            name = clean_label(match.group(1))
            if useful_name(name):
                names.add(name)
    return names


def fetch_text(url: str) -> str:
    request = urllib.request.Request(
        url,
        headers={
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
            "(KHTML, like Gecko) Chrome/125.0 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "Accept-Language": "en-US,en;q=0.9",
            "Referer": "https://comicvine.gamespot.com/",
        },
    )
    try:
        with urllib.request.urlopen(request, timeout=45) as response:
            return response.read().decode("utf-8", "ignore")
    except Exception:
        return fetch_text_with_curl(url)


def fetch_text_with_curl(url: str) -> str:
    result = subprocess.run(
        [
            "curl.exe",
            "-L",
            "-A",
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
            "(KHTML, like Gecko) Chrome/125.0 Safari/537.36",
            url,
        ],
        check=True,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="ignore",
    )
    return result.stdout


def clean_label(value: str) -> str:
    text = re.sub(r"<[^>]+>", " ", value)
    text = html.unescape(text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def useful_name(value: str) -> bool:
    text = str(value or "").strip()
    lowered = text.lower()
    if len(text) < 2 or len(text) > 90:
        return False
    blocked = {"characters", "image", "load comments"}
    return lowered not in blocked and not lowered.isdigit()


def load_data() -> dict[str, Any]:
    raw = DATA_PATH.read_text(encoding="utf-8")
    match = re.search(r"window\.AutoSheetReviewPlayerSports\s*=\s*(\{.*?\})\s*;\s*\}\)\(\);", raw, re.S)
    if not match:
        raise RuntimeError(f"Could not parse {DATA_PATH}")
    return json.loads(match.group(1))


def write_data(data: dict[str, Any]) -> None:
    payload = json.dumps(data, indent=2, ensure_ascii=False, sort_keys=True)
    DATA_PATH.write_text(
        "// Generated by category import scripts. Do not edit by hand.\n"
        "(function exposePlayerSportData() {\n"
        f"  window.AutoSheetReviewPlayerSports = {payload};\n"
        "})();\n",
        encoding="utf-8",
    )


def player_key(value: str) -> str:
    text = strip_accents(value).lower()
    text = re.sub(r"[^a-z0-9.' -]+", " ", text)
    return re.sub(r"\s+", " ", text).strip()


def strip_accents(value: str) -> str:
    return "".join(
        char
        for char in unicodedata.normalize("NFKD", str(value or ""))
        if not unicodedata.combining(char)
    )


if __name__ == "__main__":
    main()
