from __future__ import annotations

import html
import json
import re
import unicodedata
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = ROOT / "assignment_player_sport_data.js"
SOURCE_URL = "https://www.marvel.com/comics/characters"
SOURCE_NAME = "Marvel.com comics characters A-Z"


def main() -> None:
    data = load_data()
    names = fetch_marvel_names()
    players: dict[str, dict[str, Any]] = data.setdefault("players", {})
    for name in sorted(names, key=str.lower):
        key = player_key(name)
        if key:
            players[key] = {"sport": "marvel", "displayName": name}

    sources = [
        source
        for source in data.get("sources", [])
        if str(source.get("name") or "") != SOURCE_NAME
    ]
    sources.append({
        "name": SOURCE_NAME,
        "sport": "marvel",
        "url": SOURCE_URL,
        "count": len(names),
    })
    data["sources"] = sources
    data["generatedAt"] = datetime.now(timezone.utc).isoformat(timespec="milliseconds").replace("+00:00", "Z")
    write_data(data)
    print(f"Imported {len(names)} Marvel character names from {SOURCE_URL}")


def fetch_marvel_names() -> set[str]:
    request = urllib.request.Request(SOURCE_URL, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(request, timeout=45) as response:
        raw = response.read().decode("utf-8", "ignore")
    names: set[str] = set()
    for match in re.finditer(r'<a\b[^>]*href=["\']([^"\']*/characters/[^"\']*)["\'][^>]*>(.*?)</a>', raw, re.I | re.S):
        href = html.unescape(match.group(1))
        label = clean_label(match.group(2))
        if useful_name(label):
            names.add(label)
            continue
        fallback = name_from_href(href)
        if useful_name(fallback):
            names.add(fallback)
    return names


def clean_label(value: str) -> str:
    text = re.sub(r"<[^>]+>", " ", value)
    text = html.unescape(text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def name_from_href(href: str) -> str:
    slug = href.rstrip("/").split("/")[-1]
    slug = re.sub(r"^\d+-", "", slug)
    return " ".join(part.capitalize() for part in slug.replace("-", " ").split())


def useful_name(value: str) -> bool:
    text = str(value or "").strip()
    lowered = text.lower()
    if len(text) < 2 or len(text) > 90:
        return False
    blocked = {
        "characters",
        "comics",
        "load more",
        "marvel unlimited",
        "search all characters",
    }
    return lowered not in blocked


def load_data() -> dict[str, Any]:
    raw = DATA_PATH.read_text(encoding="utf-8")
    match = re.search(r"window\.AutoSheetReviewPlayerSports\s*=\s*(\{.*?\})\s*;\s*\}\)\(\);", raw, re.S)
    if not match:
        raise RuntimeError(f"Could not parse {DATA_PATH}")
    return json.loads(match.group(1))


def write_data(data: dict[str, Any]) -> None:
    payload = json.dumps(data, indent=2, ensure_ascii=False, sort_keys=True)
    DATA_PATH.write_text(
        "// Generated by category import scripts. Do not edit by hand.\n"
        "(function exposePlayerSportData() {\n"
        f"  window.AutoSheetReviewPlayerSports = {payload};\n"
        "})();\n",
        encoding="utf-8",
    )


def player_key(value: str) -> str:
    text = strip_accents(value).lower()
    text = re.sub(r"[^a-z0-9.' -]+", " ", text)
    return re.sub(r"\s+", " ", text).strip()


def strip_accents(value: str) -> str:
    return "".join(
        char
        for char in unicodedata.normalize("NFKD", str(value or ""))
        if not unicodedata.combining(char)
    )


if __name__ == "__main__":
    main()
